name: first-workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: variables
        run: |
          echo "GITHUB_ACTION===> ${{ github.action }}"
          echo "GITHUB_ACTION_PATH ...$GITHUB_ACTION_PATH"
          echo "GITHUB_EVENT_NAME  $GITHUB_EVENT_NAME"
          
        
    
