name: simle-flow
on: push
jobs:
  first-job:
    runs-on: ubuntu-22.04
    steps:
      - name: create file
        run: |
          echo "Hello testing"
          echo "=============="
          touch demo.txt
